# Generated by Django 4.0.4 on 2022-04-26 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_creation_date', models.DateTimeField()),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_articles_number', models.IntegerField(blank=True, null=True)),
                ('user_comments_number', models.IntegerField(blank=True, null=True)),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_creation_date', models.DateTimeField()),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_autohor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.user')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('article_text', models.TextField()),
                ('article_creation_date', models.DateTimeField()),
                ('article_rating', models.BooleanField(null=True)),
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('article_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.user')),
            ],
        ),
    ]
